import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { CestoProvider } from "@/context/CestoContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Agenda Aí",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <CestoProvider>
          <Navbar />
          {children}
        </CestoProvider>
      </body>
    </html>
  );
}
